### ISSUE TITLE
best.pt模型存在损坏

### ISSUE THREAD

**Issue by 511100314** [MeiHuaGuangShuo/idv-auto-player#2]
在跑
![微信图片_20241210015730](https://github.com/user-attachments/assets/3f380305-8a26-4c62-be58-38a5b148c415)
程序的时候这个pt文件显示损坏，换别的pt文件可以正常运行

**Comment by MeiHuaGuangShuo** [comment]
[best.pt.zip](https://github.com/user-attachments/files/18079031/best.pt.zip)
git上传新的好像还是不行，我压缩一个新的给你试试

**Comment by 511100314** [comment]
替换了还是损坏
![微信图片_20241210015730](https://github.com/user-attachments/assets/1ade41c9-b482-4539-b54f-17c8b42c39d1)

**Comment by 511100314** [comment]
可以发标注图片文件，我这用yolov11训练

**Comment by MeiHuaGuangShuo** [comment]
我本地没有标注图片，我是在robotflow上面标注的，这里是[链接](https://universe.roboflow.com/idv-0pww3/idv-autoplay)

**Comment by MeiHuaGuangShuo** [comment]
> 替换了还是损坏 ![微信图片_20241210015730](https://private-user-images.githubusercontent.com/68174502/394304912-1ade41c9-b482-4539-b54f-17c8b42c39d1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM5MDc0MDEsIm5iZiI6MTczMzkwNzEwMSwicGF0aCI6Ii82ODE3NDUwMi8zOTQzMDQ5MTItMWFkZTQxYzktYjQ4Mi00NTM5LWI1NGYtMTdjOGI0MmMzOWQxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjExVDA4NTE0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBmNTAyYmQxZWZkZWFjNWFhMmE4NTgyNDdmMTdjMmUwYzViNTNkYTBkNjg2ODI1ZjlkOWQxNDM3NzczMWQzNzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.9hgDrurQ2k5dieoGxm737w5a7yXNuOG6j1igIL4Jt6Y)

确实唉，本地我给你的模型在我这里运行也是错的。奇怪了，好像给git上传后就有问题了

**Comment by MeiHuaGuangShuo** [comment]
[best.pt.zip](https://github.com/user-attachments/files/18092330/best.pt.zip)
这次这个是我专门测试了可以用的，你再试试

**Comment by 511100314** [comment]
OK成功运行了，我看看能不能优化下，有些按键会没识别到没按

**Comment by MeiHuaGuangShuo** [comment]
我是尝试喂更多数据效果反而变差了，原本是300+样本后面发现效果不行就退回来了。我一般是用2速，3速概率hold不住，不过现在不玩第五人格了，而且作曲家也有自动了我倒是没什么精力去开发项目了
